apiVersion: v1
kind: Service
metadata:
  name: filestore-service
  labels:
    app: filestore
spec:
  type: NodePort
  selector:
    app: filestore
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
