apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestore-deployment
  labels:
    app: filestore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: filestore
  template:
    metadata:
      labels:
        app: filestore
    spec:
      containers:
      - name: filestore
        image: filestores:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: GIN_MODE
          value: "release"
